[package]
name = "parcel_js_swc_wasm"
authors = ["Devon Govett <devongovett@gmail.com>"]
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
parcel_js_swc_core = { path = "../core" }
wasm-bindgen = "0.2.73"
serde-wasm-bindgen = "0.1.3"
