[package]
authors = ["Devon Govett <devongovett@gmail.com>"]
name = "parcel-swc-optimizer"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "1", features = ["serde-json"] }
napi-derive = "1"
swc_ecmascript = { version = "0.44.0", features = ["codegen", "parser", "transforms", "compat", "visit"] }
swc_ecma_minifier = "0.10.0"
swc_common = { version = "0.10.21", features = ["tty-emitter", "sourcemap"] }
swc_atoms = "0.2.6"
serde = "1.0.123"

[target.'cfg(target_os = "macos")'.dependencies]
jemallocator = { version = "0.3.2", features = ["disable_initial_exec_tls"] }

[target.'cfg(windows)'.dependencies]
mimalloc = { version = "0.1.25", default-features = false }

[build-dependencies]
napi-build = { version = "1" }
